version: '3'
services:
  web:
    image: bclavijo110430/flask-basic-api:vpre1.0.0
    ports:
      - "5100:5100"
    environment:
      testingenv: cicd-dev-test-environment
      containertype: api_flask

      
      